set(SRC_DIR_SMOOTHING_IMAGE ${CMAKE_SOURCE_DIR}/smoothing_image/src)

file(GLOB SOURCES_SMOOTHING_IMAGE "${SRC_DIR_SMOOTHING_IMAGE}/*.cpp")

set(PROJECT_SOURCES_SMOOTHING_IMAGE ${SOURCES_SMOOTHING_IMAGE})

add_executable(smoothing_image ${PROJECT_SOURCES_SMOOTHING_IMAGE})