set(SRC_DIR_SMOOTHING_IMAGE_DLL ${CMAKE_SOURCE_DIR}/smoothing_image_dll/src)
set(INCLUDE_DIR_SMOOTHING_IMAGE_DLL ${CMAKE_SOURCE_DIR}/smoothing_image_dll/include)

include_directories(${INCLUDE_DIR_SMOOTHING_IMAGE_DLL})

file(GLOB SOURCES_SMOOTHING_IMAGE_DLL "${SRC_DIR_SMOOTHING_IMAGE_DLL}/*.cpp")
file(GLOB HEADERS_SMOOTHING_IMAGE_DLL "${INCLUDE_DIR_SMOOTHING_IMAGE_DLL}/*.hpp" "${INCLUDE_DIR_SMOOTHING_IMAGE_DLL}/*.h")

set(PROJECT_SOURCES_SMOOTHING_IMAGE_DLL ${SOURCES_SMOOTHING_IMAGE_DLL} ${HEADERS_SMOOTHING_IMAGE_DLL})

add_library(smoothing_image_dll SHARED ${PROJECT_SOURCES_SMOOTHING_IMAGE_DLL})

target_compile_definitions(smoothing_image_dll PUBLIC SMOOTHING_IMAGE_DLL_SOURCE)